### ISSUE TITLE
Poll PI to check for new requests

### ISSUE THREAD

**Issue by cranmer** [recast-hep/recast-frontend-prototype#11]
Ideally PI's server would ping this front-end to initiate it.

**Comment by lukasheinrich** [comment]
is this a real use case? simple reload of a page would include any new requests as they're fetched from PI via API. do we need to support real time update?

**Comment by cranmer** [comment]
The idea was not for the user interface, but to trigger the processing.
If user added request to PI front end it would be nice if that triggered processing similar to adding it on the prototype front end.

Kyle

**Comment by lukasheinrich** [comment]
if the user creates a new request or parameter point on the PI website this will show up on prototype frontend with a process button. so the behavior is the same no matter where the request was created.

sample request I created @ PI website
http://recast-demo.cern.ch:8000/recast/request/738f59db-eea8-24f4-7dd0-a1d32db3e1c8

**Comment by cranmer** [comment]
I see. works here:
http://localhost:8000/recast/request/f231659f-7cfe-2d74-2986-682cac81ad47
corresponding to
http://recast.perimeterinstitute.ca/dev/?q=node/530
