### ISSUE TITLE
title change

### ISSUE THREAD

**Issue by cranmer** [recast-hep/recast-frontend-prototype#5]
LHC data reinterpreted -> An Analysis Reinterpretation Framework

Change text below Introduction to
This is an early prototype for the RECAST framework. This web application communicates with the RECAST front-end at http://recast.perimeterinstitute.ca and provides a plugin model for analyses.

Please add 

Links & Related Projects:
- original white paper - http://arxiv.org/abs/1010.2506
- ATLAS Data Access Policy - https://twiki.cern.ch/twiki/pub/AtlasPublic/AtlasPolicyDocuments/A78_ATLAS_Data_Access_Policy.pdf
- RECAST in DPHEP http://arxiv.org/pdf/1205.4667.pdf
- DASPOS - https://daspos.crc.nd.edu
- CERN Analysis Preservation Demo - http://data-demo.cern.ch

**Comment by lukasheinrich** [comment]
done
