### ISSUE TITLE
Separate Rivet/hype/atom/checkmate/madanalysis backends

### ISSUE THREAD

**Issue by cranmer** [recast-hep/recast-frontend-prototype#9]
Not sure what the best navigation is here, may need to experiment.
Different drop downs won't scale well if more services become available.

Also, a single analysis might have multiple backends available.
Maybe start with navigation, but eventually probably want to be able to look at all analyses and filter by which ones have backends satisfying various conditions.

**Comment by lukasheinrich** [comment]
implemented.
